### ISSUE TITLE
InterfaceError at /admin/multifactor/totp/new/ Error binding parameter 2 - probably unsupported type.

### ISSUE THREAD

**Issue by 9mido** [oliwarner/django-multifactor#8]
Got this error after trying to verify by TOTP with Google Authenticator. I did not decorate a view and did the same exact steps in the docs up to the Usage section. 

```
Internal Server Error: /admin/multifactor/totp/new/
Traceback (most recent call last):
  File "/home/user/.local/share/virtualenvs/app/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/home/user/.local/share/virtualenvs/app/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 396, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.InterfaceError: Error binding parameter 2 - probably unsupported type.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/.local/share/virtualenvs/app/lib/python3.7/site-packages/django/db/backends/utils.py", line 110, in debug_sql
    yield
  File "/home/user/.local/share/virtualenvs/app/lib/python3.7/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/user/.local/share/virtualenvs/app/lib/python3.7/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/user/.local/share/virtualenvs/app/lib/python3.7/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/user/.local/share/virtualenvs/app/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/home/user/.local/share/virtualenvs/app/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/user/.local/share/virtualenvs/app/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/home/user/.local/share/virtualenvs/app/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 396, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.InterfaceError: Error binding parameter 2 - probably unsupported type.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/share/virtualenvs/app/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/user/.local/share/virtualenvs/app/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/user/.local/share/virtualenvs/app/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/user/.local/share/virtualenvs/app/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/user/.local/share/virtualenvs/app/lib/python3.7/site-packages/multifactor/factors/totp.py", line 22, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/user/.local/share/virtualenvs/app/lib/python3.7/site-packages/django/contrib/auth/mixins.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/user/.local/share/virtualenvs/app/lib/python3.7/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/user/.local/share/virtualenvs/app/lib/python3.7/site-packages/multifactor/factors/totp.py", line 39, in post
    key_type=KEY_TYPE_TOPT
  File "/home/user/.local/share/virtualenvs/app/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/user/.local/share/virtualenvs/app/lib/python3.7/site-packages/django/db/models/query.py", line 433, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/user/.local/share/virtualenvs/app/lib/python3.7/site-packages/django/db/models/base.py", line 746, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/user/.local/share/virtualenvs/app/lib/python3.7/site-packages/django/db/models/base.py", line 784, in save_base
    force_update, using, update_fields,
  File "/home/user/.local/share/virtualenvs/app/lib/python3.7/site-packages/django/db/models/base.py", line 887, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/home/user/.local/share/virtualenvs/app/lib/python3.7/site-packages/django/db/models/base.py", line 926, in _do_insert
    using=using, raw=raw,
  File "/home/user/.local/share/virtualenvs/app/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/user/.local/share/virtualenvs/app/lib/python3.7/site-packages/django/db/models/query.py", line 1204, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/user/.local/share/virtualenvs/app/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1392, in execute_sql
    cursor.execute(sql, params)
  File "/home/user/.local/share/virtualenvs/app/lib/python3.7/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/user/.local/share/virtualenvs/app/lib/python3.7/site-packages/django/db/backends/utils.py", line 115, in debug_sql
    sql = self.db.ops.last_executed_query(self.cursor, sql, params)
  File "/home/user/.local/share/virtualenvs/app/lib/python3.7/site-packages/django/db/backends/sqlite3/operations.py", line 152, in last_executed_query
    params = self._quote_params_for_last_executed_query(params)
  File "/home/user/.local/share/virtualenvs/app/lib/python3.7/site-packages/django/db/backends/sqlite3/operations.py", line 141, in _quote_params_for_last_executed_query
    return cursor.execute(sql, params).fetchone()
sqlite3.InterfaceError: Error binding parameter 2 - probably unsupported type.
```

**Comment by oliwarner** [comment]
django-multifactor currently requires Postgres for a sane implementation of JSONField.

Django 3.1 (in beta currently) has a cross-database version built-in so we'll port to that. Hell, I'll write that patch now so you can choose to use Django 3.1 if you want to not use Postgres. Django is advertising the following support for 3.1.

> JSONField is supported on MariaDB 10.2.7+, MySQL 5.7.8+, Oracle, PostgreSQL, and SQLite 3.9.0+ (with the JSON1 extension enabled).

I'll update this when the new version is released.

**Comment by 9mido** [comment]
Awesome good to know @oliwarner ! Thanks for the quick response.

**Comment by oliwarner** [comment]
This _should_ be usable with Django==3.1beta1 on other databases. Let me know.
